const APICALLREFRESH = "APICALLREFRESH";
const OPENMODAL = "OPENMODAL";
const CURRENTCULTUREVALUE = "CURRENTCULTUREVALUE";
const ACRTIVEFORMBTN = "ACTIVEBTN";
const EDITISON = "EDITISON";
const ADDCULTUREACTION = "ADDCULTUREACTION";
export {
  APICALLREFRESH,
  OPENMODAL,
  CURRENTCULTUREVALUE,
  ACRTIVEFORMBTN,
  EDITISON,
  ADDCULTUREACTION,
};
